/* BaseQ2 player-side constants from g_local.h/p_client.c. */
package miniquake2.game.player.constants

const MOVETYPE_NONE = 0
const MOVETYPE_WALK = 3
const MOVETYPE_NOCLIP = 8
const MOVETYPE_TOSS = 6

const DAMAGE_NO = 0
const DAMAGE_YES = 1
const DAMAGE_AIM = 2

const DEAD_NO = 0
const DEAD_DYING = 1
const DEAD_DEAD = 2

const BODY_QUEUE_SIZE = 8
const FRAME_TIME = 0.1
const DAMAGE_TIME = 0.5
const FALL_TIME = 0.3
const FL_INWATER = 0x00000008

const ANIM_BASIC = 0
const ANIM_WAVE = 1
const ANIM_JUMP = 2
const ANIM_PAIN = 3
const ANIM_ATTACK = 4
const ANIM_DEATH = 5
const ANIM_REVERSE = 6

const FRAME_STAND_FIRST = 0
const FRAME_STAND_LAST = 39
const FRAME_RUN_FIRST = 40
const FRAME_RUN_LAST = 45
const FRAME_ATTACK_FIRST = 46
const FRAME_ATTACK_LAST = 53
const FRAME_PAIN1_FIRST = 54
const FRAME_PAIN1_LAST = 57
const FRAME_PAIN2_FIRST = 58
const FRAME_PAIN2_LAST = 61
const FRAME_PAIN3_FIRST = 62
const FRAME_PAIN3_LAST = 65
const FRAME_JUMP_FIRST = 66
const FRAME_JUMP_LAST = 67
const FRAME_JUMP_LAND_FIRST = 68
const FRAME_JUMP_LAND_LAST = 71
const FRAME_CROUCH_STAND_FIRST = 135
const FRAME_CROUCH_STAND_LAST = 153
const FRAME_CROUCH_WALK_FIRST = 154
const FRAME_CROUCH_WALK_LAST = 159
const FRAME_CROUCH_ATTACK_FIRST = 160
const FRAME_CROUCH_ATTACK_LAST = 168
const FRAME_CROUCH_PAIN_FIRST = 169
const FRAME_CROUCH_PAIN_LAST = 172
const FRAME_CROUCH_DEATH_FIRST = 173
const FRAME_CROUCH_DEATH_LAST = 177
const FRAME_DEATH1_FIRST = 178
const FRAME_DEATH1_LAST = 183
const FRAME_DEATH2_FIRST = 184
const FRAME_DEATH2_LAST = 189
const FRAME_DEATH3_FIRST = 190
const FRAME_DEATH3_LAST = 197

const MOD_WATER = 17
const MOD_SLIME = 18
const MOD_LAVA = 19
const MOD_CRUSH = 20
const MOD_TELEFRAG = 21
const MOD_FALLING = 22
const MOD_SUICIDE = 23
const MOD_HELD_GRENADE = 24
const MOD_EXPLOSIVE = 25
const MOD_BARREL = 26
const MOD_BOMB = 27
const MOD_EXIT = 28
const MOD_SPLASH = 29
const MOD_TARGET_LASER = 30
const MOD_TRIGGER_HURT = 31
const MOD_HIT = 32
const MOD_TARGET_BLASTER = 33

const PLAYER_MODEL_INDEX = 255
const DEFAULT_GRAVITY = 800
const DEFAULT_FOV = 90
const MAX_FOV = 160
